imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        
knp_snappy:
    temporary_folder: C:\wamp64\bin\php\php7.2.4\DBExample\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\temp\
    pdf:
        enabled:    true
        binary:     C:\wamp64\bin\php\php7.2.4\DBExample\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     C:\wamp64\bin\php\php7.2.4\DBExample\vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf
        options:    []

easy_admin:
    site_name: 'Interniet Plush'
    list:
      max_results: 20
    design:
      assets:
        css:
          # - '//example.org/css/admin1.css'
        js:
          # - '//example.org/js/admin1.js'
      menu:
        - label: 'Objects'
          children:
            - { entity: 'Mark', label: 'Marks', icon: 'tag', default: true} #The 'default: true' parameter sets the default view when loading admin panel
            - { entity: 'Student'}
            - { entity: 'Classes', label: 'Classes'}
        - { label: '-------------------------------' }
        - { label: 'Go to App', url: '../student/display' }
    entities:
        # change the following to the namespaces of your own entities
        Student:
          class: AppBundle\Entity\Student
          help: 'This is a entity specific message!'
          label: 'Students'
          list:
            title: 'List of all %%entity_label%%'
            max_results: 5
            fields: [{property: 'IDName', label: 'ID + name', type: 'string'}, { property: 'id', label: 'L.p.', type: 'smallint' }, 'name', {property: 'classes'}, 'marks', 'address', 'active']
          show:
            title: '%%entity_label%% (#%%entity_id%%)'
          search:
          #when displaying search result, sort them by field 'name'
            sort: ['name', 'ASC']
        Classes: AppBundle\Entity\Classes
        Mark:
          help: "This is a custom mark message"
          class: AppBundle\Entity\Mark
          form:  # 'form' is applied to both 'new' and 'edit' views
            title: 'Add mark'
          edit:
            help: null #This cancels the help message
            title: 'Edit mark'
            fields:
              - {property: 'id'}
              - {property: 'markValue'}
          list:
            # By default the dql_filter option from the list view is also used in the search view.
            dql_filter: "entity.markValue > 3 AND entity.markValue < 7 AND entity.id != '24'"
          search:
            # override, since search by default uses the same filter rules as list view
            dql_filter: ''