<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.dnot1vr' shared service.

return $this->services['service_locator.dnot1vr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('logger' => function () {
    return ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'};
}));
