<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Student extends \AppBundle\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'classes', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'marks'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'classes', '' . "\0" . 'AppBundle\\Entity\\Student' . "\0" . 'marks'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Student $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function checkIfAttendsClass(\AppBundle\Entity\Classes $class): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkIfAttendsClass', [$class]);

        return parent::checkIfAttendsClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentMarksAverageForClass(\AppBundle\Entity\Classes $class): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentMarksAverageForClass', [$class]);

        return parent::getStudentMarksAverageForClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function getIDName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDName', []);

        return parent::getIDName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function addClass(\AppBundle\Entity\Classes $class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClass', [$class]);

        return parent::addClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClass(\AppBundle\Entity\Classes $class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClass', [$class]);

        return parent::removeClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasses', []);

        return parent::getClasses();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarks', []);

        return parent::getMarks();
    }

    /**
     * {@inheritDoc}
     */
    public function addMark(\AppBundle\Entity\Mark $mark)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMark', [$mark]);

        return parent::addMark($mark);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMark(\AppBundle\Entity\Mark $mark)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMark', [$mark]);

        return parent::removeMark($mark);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

}
