<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO6ujvni\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO6ujvni/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO6ujvni.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO6ujvni\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerO6ujvni\appTestDebugProjectContainer(array(
    'container.build_hash' => 'O6ujvni',
    'container.build_id' => '0a9c15d4',
    'container.build_time' => 1530006990,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO6ujvni');
