<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHc9xzzj\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHc9xzzj/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHc9xzzj.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHc9xzzj\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerHc9xzzj\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Hc9xzzj',
    'container.build_id' => 'c52fd67c',
    'container.build_time' => 1530001746,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHc9xzzj');
