<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyvg4xq\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyvg4xq/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSyvg4xq.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSyvg4xq\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerSyvg4xq\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Syvg4xq',
    'container.build_id' => 'dcac2c75',
    'container.build_time' => 1529495037,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyvg4xq');
