<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxx3aqp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxx3aqp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOxx3aqp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOxx3aqp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOxx3aqp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Oxx3aqp',
    'container.build_id' => '74ec6a0c',
    'container.build_time' => 1529588526,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxx3aqp');
