<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xlsxaf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xlsxaf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7xlsxaf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7xlsxaf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7xlsxaf\appDevDebugProjectContainer(array(
    'container.build_hash' => '7xlsxaf',
    'container.build_id' => 'e80751e9',
    'container.build_time' => 1530001579,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7xlsxaf');
